### ISSUE TITLE
Cookiemonsters - 2020/10/20

### ISSUE THREAD

**Issue by tadeuasarro** [thneves/Tic-Tac-Toe-Game#3]
### Optional: Too many variables
- I believe there are too many variables for one purpose, we can see that there are a class variable and an instance variable for Turn, maybe that could be worked on.
- [Check this](https://www.rubyguides.com/ruby-tutorial/variables/)

### Work on the relations between the classes could prove useful, below the first two objects are passed parameters to the third.
- ```player1 = Player.new(Jorge)```
- ```player2 = Player.new(Tadeu)```
- ```game = Game.new(player1, player2)```

**Comment by Jhdezj** [comment]
Thank you guys we implemented the changes as suggested.
