### ISSUE TITLE
Separation of concerns design pattern is not followed.

### ISSUE THREAD

**Issue by RaminMammadzada** [thneves/Tic-Tac-Toe-Game#4]
First of all, your file structure is not right.
you should put your entity classes into extra ```lib``` folder in the root directory of your app. What I mean is that you should create ```player.rb``` file inside your ```lib``` folder and create the only Player class inside that ```player.rb``` file.

Then inside your ```main.rb``` file or inside another file, you can require your Player class and create Player instance. 
This kind of separation is generally known as Separation Of Concerns pattern in object-oriented programming.

**Comment by thneves** [comment]
- Organize structure, create more methods and classes

**Comment by Jhdezj** [comment]
We separated the files as suggested. Thank you guys.
